### ISSUE TITLE
Example JSON doesn't work with Grafana 4.1

### ISSUE THREAD

**Issue by robfig** [grafana-tools/sdk#1]
Summary: The Example produces JSON that can not be imported by Grafana 4.1

I'm trying to write a program that posts a dashboard to my new Grafana 4.1 instance, but I can't get it working. The JSON returned from the server is "[]". I reproduced this issue using the [Example JSON](https://godoc.org/github.com/grafana-tools/sdk#NewBoard) given in the docs, and through trial and error using the interactive JSON import narrowed the problem down to this part:

```
      "grid": {
            "leftLogBase": null,
            "leftMax": null,
            "leftMin": null,
            "rightLogBase": null,
            "rightMax": null,
            "rightMin": null,
            "threshold1": null,
            "threshold1Color": "",
            "threshold2": null,
            "threshold2Color": "",
            "thresholdLine": false
          },
```

Including the "grid" key at all (even without sub-keys) causes the dashboard to fail after import, and I assume it's the same issue when doing it programmatically. I don't know enough about Grafana to say why this is the case or what the right resolution is. However, it does seem weird because looking at the JSON for existing dashboards shows the same "grid" key. So maybe this is a red herring.

**Comment by grafov** [comment]
Thank you for report and explanation of the problem. It seems latest Grafana versions changed scheme for definition X and Y axes, so `grid` structure is obsoleted. I made a quick fix.

**Comment by robfig** [comment]
The new JSON seems to work, thank you! Will do more testing
