### ISSUE TITLE
Add ability to add Links to dashboards

### ISSUE THREAD

**Issue by sinkingpoint** [grafana-tools/sdk#104]
Current dashboards have a field `Links` which is a slice of a private field `link`. Because this field is private, we're not able to construct new links to add to dashboards. Is there any reason why this struct isn't exported? Can we just export it?

**Comment by GiedriusS** [comment]
TBH I don't know why it has been written this way. I don't see anything wrong with exposing it albeit it would be a breaking change but that's fine since we still aren't providing any guarantees.
