### ISSUE TITLE
panel UnmarshalJSON missing row

### ISSUE THREAD

**Issue by jinnzy** [grafana-tools/sdk#107]
Hi,When I import the dashboard, the collapsed panel is missing
![image](https://user-images.githubusercontent.com/33449123/91799814-68f01e00-ec5a-11ea-9503-e6bc5536dae6.png)

The reason is rowPanel json.Unmarshal customPanel

After adding the above code, it can be imported normally. Why is rowPanel missing?
![image](https://user-images.githubusercontent.com/33449123/91800081-f2075500-ec5a-11ea-99dc-e8ea37c35512.png)

**Comment by laghoule** [comment]
Same problem with `gauge`.
I have use this to fix on my fork:
```golang
		case "singlestat", "gauge":
			var singlestat SinglestatPanel
			p.OfType = SinglestatType
			if err = json.Unmarshal(b, &singlestat); err == nil {
				p.SinglestatPanel = &singlestat
			}
```
It's a ugly hack, but seem to work with my dashboard.

**Comment by jinnzy** [comment]
If this is a problem, can I submit a pr?

**Comment by laghoule** [comment]
I have switched to using github.com/grafana/grafana-api-golang-client

**Comment by GiedriusS** [comment]
What version of Grafana are you using?

> I have switched to using github.com/grafana/grafana-api-golang-client

I'm glad you've found something that works for you but let's please talk about this project here.

**Comment by jinnzy** [comment]
> What version of Grafana are you using?
> 
> > I have switched to using github.com/grafana/grafana-api-golang-client
> 
> I'm glad you've found something that works for you but let's please talk about this project here.

v7.1.2 and v6.7.4

**Comment by jd4900** [comment]
Is there a PR or a fork that has this code?

**Comment by GiedriusS** [comment]
I have added this code to `master`. Should work now as per the original issue. Please scream if it still doesn't work and I will reopen. There isn't any particular reason the case isn't there, we simply missed it originally.
