### ISSUE TITLE
Target has no measurement field

### ISSUE THREAD

**Issue by jd4900** [grafana-tools/sdk#114]
There is no Measurement field in the Target structure which forces a measurement to be dropped when retrieving a dashboard JSON. 

When unmarshalling a JSON created in the UI that uses InfluxDB as it's datasource the measurement field is dropped. The current struct lists various fields for various types of datasources but does not have a section for fields for InfluxDB. 

Are there any other fields that should be added? I've added the measurement field in my own fork [here](https://github.com/jd4900/sdk) but am wondering if there are any fields I am missing.

**Comment by GiedriusS** [comment]
You are correct that there are other fields missing. Ideally, we'd have all of them listed out. However, Grafana gets updated at a rapid pace and we support two different major versions so now thus I'm not sure how much of a good idea it would be to add all of them right now _without_ physically separating the v6 and v7 models.

**Comment by jd4900** [comment]
Issue fixed in #115
