### ISSUE TITLE
Migrate to GH actions from TravisCI

### ISSUE THREAD

**Issue by GiedriusS** [grafana-tools/sdk#120]
TravisCI doesn't work anymore so migrate to GH actions instead :hugs:

**Comment by grafov** [comment]
Ok, it seems I missed something important. travis-ci.com says "Testing your open source projects is always 100% free! " It seems they are still offer free access for open source projects. Is it true? Ok we can try GH actions I just not tried them for go builds yet.

**Comment by GiedriusS** [comment]
https://news.ycombinator.com/item?id=25338983 this provides some information. I'm not sure for how much longer this will work :(

**Comment by GiedriusS** [comment]
@grafov https://github.com/grafana-tools/sdk/pull/123 on this PR it is already not running :( may I have more rights on this repo so that I could switch to GH actions? Plus, https://travis-ci.org/ is being migrated to ".com" so that could be the culprit as well.

**Comment by grafov** [comment]
Sorry for the silence. I'll add permissions to you if it possible asap.

**Comment by grafov** [comment]
@GiedriusS, I've sent you invite to the project as the co-owner. Is it apropriate for you? I think after accept you'll have get the permissions you need for this task.

**Comment by safaci2000** [comment]
If you're still looking to migrate this, https://cloud.drone.io/ is another option.  Free for OSS projects.

**Comment by GiedriusS** [comment]
Successfully migrated away from Travis to GH actions :P
