### ISSUE TITLE
UserListing Discrepancy

### ISSUE THREAD

**Issue by safaci2000** [grafana-tools/sdk#145]
GET /api/users uses the flag "isAdmin" to flag the user as an Admin.
GET /api/users/:id uses the flag "isGrafanaAdmin" to flag the user as an Admin.

Since both responses in the API use the same sdk.Model, the behavior is inconsistent and is reporting the wrong value.

specifically, client.GetAllUsers will never return IsGrafanaAdmin true.

**Comment by GiedriusS** [comment]
Closing this as I've merged https://github.com/grafana-tools/sdk/pull/146
