### ISSUE TITLE
compatibility matrix

### ISSUE THREAD

**Issue by mbenabda** [grafana-tools/sdk#17]
hello,

could you please provide a compatibility matrix for versions of the sdk regarding versions of the grafana API ([here is an example of a pretty informative one](https://github.com/kubernetes/client-go#compatibility-matrix)) ? 

or at least mention the supported grafana API version for the latest version

Thank you !

**Comment by grafov** [comment]
Yes it would be nice to have such matrix. I have left the company where we used this SDK so currently active development is not high priority for me. But I have plan to complete and stabilize the code. I think it would be reasonable update the SDK up to latest Grafana API without tracking of compatibility issues. Then provide compatibility matrix when SDK become stable version 1.0.

**Comment by mbenabda** [comment]
that makes sense, thanks for the answer
