### ISSUE TITLE
Roadmap/Additional Endpoint Implementation

### ISSUE THREAD

**Issue by mlclmj** [grafana-tools/sdk#19]
Hi,

I'm looking into the possibility of switching the Grafana provider for Terraform to use this SDK instead of an independent client, however it doesn't appear that this SDK includes any implementation for Grafana Alert Notifications. Is this on the roadmap to be implemented at all in the near future?

We'd be interested in contributing to the SDK as well to further it's development! However, is there anyone actively maintaining it/reviewing PRs at this time? 

Thanks,
Malcolm

**Comment by grafov** [comment]
Sadly there is not clear roadmap yet. I used this SDK for my previous job but currently it is not required for me. Anyway I continue to support the project and review incoming PRs. I ready to add more maintainers and project owners for keeping maintainance responsible.

**Comment by 0verc1ocker** [comment]
> however it doesn't appear that this SDK includes any implementation for Grafana Alert Notifications.

I'm also interested in a feature to support Grafana Alert Notifications. Is there any other interest? @mlclmj did you figure out another way to support this?

**Comment by mlclmj** [comment]
Hey @0verc1ocker -- take a look at [go-grafana-api's alert notifications](https://github.com/nytm/go-grafana-api/blob/master/alertnotification.go), that might have what you're looking for!

**Comment by GiedriusS** [comment]
I have made this https://github.com/grafana-tools/sdk/pull/53 because we were using this `sdk` already and it seems like it works. However, having some integration tests in this repo itself would be nice.

**Comment by GiedriusS** [comment]
That API has been implemented some time ago and new end-points are being added. Even though there is no roadmap but please feel free to open up a separate issue for any missing APIs. I became a maintainer a few months ago and I am and I plan on continuing to review & merge PRs so please feel free to contribute. Thanks :heart:
