### ISSUE TITLE
Is PR welcomed?

### ISSUE THREAD

**Issue by fredwangwang** [grafana-tools/sdk#40]
I am working on a project which needs to interact with grafana. While this seems the official repo for the sdk, it lacks a lot of functionalities I need. If PR welcomed, I can contribute back the functionalities I found useful and add it back here.

**Comment by grafov** [comment]
The project has no official relations to the Grafana project, it is independent effort.
PR very welcomed :) I do not actively contribute to the project anymore but continue to maintain it and use the results for my work. So I interested in SDK improvements.
