### ISSUE TITLE
c.GetActualOrg undefined (type *sdk.Client has no field or method GetActualOrg)

### ISSUE THREAD

**Issue by Aisuko** [grafana-tools/sdk#81]
Hi, there may some issue needs be help

The code below

```
	c := sdk.NewClient(BaseURL, APIKey, g.httpClient)
	if _, err := c.GetActualOrg(); err != nil {
		err = errors.Wrapf(err, "connection to grafana failed")
		logrus.Error(err)
		return err
	}
```

Got error:

`c.GetActualOrg undefined (type *sdk.Client has no field or method GetActualOrg)`

And I saw the `README.md` with go version support

```
1.13.x
1.12.x
1.11.x
```

My go version 

`go version go1.14.1 darwin/amd64`

Is there any plan to support the latest go version? Maybe I can contribute to support the latest go version

**Comment by GiedriusS** [comment]
Hello,

> Hi, there may some issue needs be help
> 
> The code below
> 
> ```
> 	c := sdk.NewClient(BaseURL, APIKey, g.httpClient)
> 	if _, err := c.GetActualOrg(); err != nil {
> 		err = errors.Wrapf(err, "connection to grafana failed")
> 		logrus.Error(err)
> 		return err
> 	}
> ```
> 
> Got error:
> 
> `c.GetActualOrg undefined (type *sdk.Client has no field or method GetActualOrg)`
> 
> And I saw the `README.md` with go version support
> 
> ```
> 1.13.x
> 1.12.x
> 1.11.x
> ```
> 
> My go version
> 
> `go version go1.14.1 darwin/amd64`
> 
> Is there any plan to support the latest go version? Maybe I can contribute to support the latest go version

Thanks for using this. It should work fine with `1.14.1`. I have noticed that in your snippet you have:

> 	if _, err := c.GetActualOrg(); err != nil {

I have recently changed so that methods which do requests would accept a `context.Context` like all proper Go libraries do:

https://github.com/grafana-tools/sdk/blob/f0431e44c1c35b20751dc4c210a00b4c0d09d1d5/rest-org.go#L76

Maybe that's why you are getting that error? Does it help if you add `context.Background()` as the first argument?

**Comment by Aisuko** [comment]
@GiedriusS Thanks for your reply. Yes, we use your tool-kit in our project(https://github.com/layer5io/meshery). So powerful tool, ha. I'm sorry for did not show you with my used tool kit version

https://github.com/layer5io/meshery/blob/61e90966b9423bf94e6462541af1d7d0bed5c0e5/go.mod#L19

I saw the error like below and I think the  `grafana-toolkit ` I used did not change the function `GetActualOrg()` 

![Screen Shot 2020-04-10 at 10 02 11 AM](https://user-images.githubusercontent.com/8053949/78955619-5a219700-7b12-11ea-87c1-2639275ce797.png)

**Comment by GiedriusS** [comment]
> @GiedriusS Thanks for your reply. Yes, we use your tool-kit in our project(https://github.com/layer5io/meshery). So powerful tool, ha. I'm sorry for did not show you with my used tool kit version
> 
> https://github.com/layer5io/meshery/blob/61e90966b9423bf94e6462541af1d7d0bed5c0e5/go.mod#L19
> 
> I saw the error like below and I think the `grafana-toolkit ` I used did not change the function `GetActualOrg()`
> 

Yes and it seems like your editor for some reason retrieved the newest version or something else is wrong because in your `go.mod` you are pinned to https://github.com/grafana-tools/sdk/commit/83ac18ae3b6c which still has that method without `context.Context`. Not sure how can I help you more :/

**Comment by GiedriusS** [comment]
I have added builds with 1.14.x to this PR https://github.com/grafana-tools/sdk/pull/78 and it seems to build just fine modulo the linter errors :confused:

**Comment by Aisuko** [comment]
That's ok. We will try to find something deep

**Comment by GiedriusS** [comment]
> That's ok. We will try to find something deep

Thanks! Let me know if you find anything. If everything's OK then don't forget to close this ticket :-)

**Comment by Aisuko** [comment]
> > That's ok. We will try to find something deep
> 
> Thanks! Let me know if you find anything. If everything's OK then don't forget to close this ticket :-)

For sure.

**Comment by Aisuko** [comment]
@GiedriusS  Hi, I have considered here https://pkg.go.dev/github.com/grafana-tools/sdk@v0.0.0-20190705114053-83ac18ae3b6c?tab=doc . The version `83ac18a` did not include the function `GetActualOrg` Is there any idea on this?

**Comment by Aisuko** [comment]
I'm not sure what happened here actually. So, I'd like to try to upgrade the SDK version to the latest. The latest version is working well. So, close the issue.
