### ISSUE TITLE
Generate dashboard failed

### ISSUE THREAD

**Issue by breeze7086** [grafana-tools/sdk#90]
Grafana Version: v7.0.3
Test code:
```
board := sdk.NewBoard("Sample dashboard title")
c := sdk.NewClient("<https url>", "<api key with admin role>", sdk.DefaultHTTPClient)
	response, err := c.SetDashboard(context.TODO() ,*board, sdk.SetDashboardParams{
		Overwrite: false,
	})
if err != nil {
	fmt.Printf("error on uploading dashboard %s", board.Title)
} else {
	fmt.Printf("dashboard URL: %v", grafanaURL+*response.URL)
}
```

Error:
![image](https://user-images.githubusercontent.com/2194003/84641424-8fd96680-af2d-11ea-8368-19335a9d7d37.png)

**Comment by breeze7086** [comment]
The code executive successfully and prints the URL of the dashboard.
But when open the Grafana console to see detail, it shows error like the pic.

**Comment by GiedriusS** [comment]
Hi! Yep, we still haven't added tests for 7.x Grafana. This part in general doesn't have integration tests. Help wanted!

**Comment by ldb** [comment]
@breeze7086 did you find any fix or workaround for this? I am seeing similar behaviour on Grafana v7.2.1.

**Comment by GiedriusS** [comment]
Seems like this is the same problem as https://github.com/grafana-tools/sdk/issues/83. Shall we close this?

**Comment by ldb** [comment]
Yes, I think we can. In my specific case I was editing an existing Dashboard and did not notice it was malformed.
