### ISSUE TITLE
Support for PostgreSQL as datasource

### ISSUE THREAD

**Issue by GustavJaner** [grafana-tools/sdk#92]
https://grafana.com/docs/grafana/latest/features/datasources/
Grafana supports a number of data sources that are not specified as examples in the Target type https://godoc.org/github.com/grafana-tools/sdk#Target

I'm looking for a way to integrate a Postgresql through this SDK. Is that possible?

**Comment by GiedriusS** [comment]
It seems like the answer is no. Feel free to add needed members to that struct to also support PostgreSQL.
